/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Gestion_membres (void)
{
  GtkWidget *Gestion_membres;
  GtkWidget *fixed49;
  GtkWidget *label529;
  GtkWidget *hbuttonbox1;
  GtkWidget *home;
  GtkWidget *image75;
  GtkWidget *statistique;
  GtkWidget *alignment58;
  GtkWidget *hbox56;
  GtkWidget *image79;
  GtkWidget *label601;
  GtkWidget *histogramme;
  GtkWidget *alignment59;
  GtkWidget *hbox57;
  GtkWidget *image80;
  GtkWidget *label603;
  GtkWidget *gestion;
  GtkWidget *fixed50;
  GtkWidget *fixed54;
  GtkWidget *entrynom;
  GtkWidget *entryprenom;
  GtkWidget *entryid;
  GtkWidget *entryemail;
  GtkWidget *entrymdp;
  GtkWidget *entrytel;
  GtkWidget *entryadressee;
  GtkObject *jour1_adj;
  GtkWidget *jour1;
  GtkObject *mois1_adj;
  GtkWidget *mois1;
  GtkObject *annee1_adj;
  GtkWidget *annee1;
  GtkWidget *entry122;
  GtkWidget *label554;
  GtkWidget *annee;
  GtkWidget *sexe;
  GtkWidget *femme;
  GSList *femme_group = NULL;
  GtkWidget *homme;
  GtkWidget *poids;
  GtkWidget *mois;
  GtkWidget *jour;
  GtkWidget *prenom;
  GtkWidget *ajouter;
  GtkWidget *alignment46;
  GtkWidget *hbox44;
  GtkWidget *image57;
  GtkWidget *label572;
  GtkWidget *annuler;
  GtkWidget *alignment47;
  GtkWidget *hbox45;
  GtkWidget *image58;
  GtkWidget *label573;
  GtkWidget *message;
  GtkWidget *nom;
  GtkWidget *email;
  GtkWidget *id;
  GtkWidget *date;
  GtkWidget *adresse;
  GtkWidget *tel;
  GtkWidget *mdp;
  GtkWidget *image74;
  GtkWidget *ajouterb;
  GtkWidget *fixed51;
  GtkWidget *entryId;
  GtkWidget *entrynomn;
  GtkWidget *entryprenomn;
  GtkWidget *entryidn;
  GtkWidget *entryemailn;
  GtkWidget *entrymdpn;
  GtkWidget *entryteln;
  GtkWidget *entryadressen;
  GtkObject *nouvjour1_adj;
  GtkWidget *nouvjour1;
  GtkObject *nouvmois1_adj;
  GtkWidget *nouvmois1;
  GtkObject *nouvannee1_adj;
  GtkWidget *nouvannee1;
  GtkWidget *entrypoidsn;
  GtkWidget *radiobutton46;
  GSList *radiobutton46_group = NULL;
  GtkWidget *radiobutton47;
  GtkWidget *label555;
  GtkWidget *nouvprenom;
  GtkWidget *nouvnom;
  GtkWidget *nouvmois;
  GtkWidget *nouvannee;
  GtkWidget *nouvsexe;
  GtkWidget *nouvpoids;
  GtkWidget *nouvjour;
  GtkWidget *Id;
  GtkWidget *nouvid;
  GtkWidget *chercher;
  GtkWidget *image64;
  GtkWidget *modifier;
  GtkWidget *alignment48;
  GtkWidget *hbox46;
  GtkWidget *image59;
  GtkWidget *label574;
  GtkWidget *annulern;
  GtkWidget *alignment49;
  GtkWidget *hbox47;
  GtkWidget *image60;
  GtkWidget *label575;
  GtkWidget *nouvemail;
  GtkWidget *nouvmdp;
  GtkWidget *nouvtel;
  GtkWidget *nouvadresse;
  GtkWidget *nouvdate;
  GtkWidget *message2;
  GtkWidget *modifierb;
  GtkWidget *fixed53;
  GtkWidget *label579;
  GtkWidget *entryidd;
  GtkWidget *treeview4;
  GtkWidget *idd;
  GtkWidget *recherche;
  GtkWidget *alignment52;
  GtkWidget *hbox50;
  GtkWidget *image63;
  GtkWidget *label580;
  GtkWidget *afficher;
  GtkWidget *alignment53;
  GtkWidget *hbox51;
  GtkWidget *image66;
  GtkWidget *label581;
  GtkWidget *label582;
  GtkWidget *label583;
  GtkWidget *chercherb;

  Gestion_membres = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_membres), _("gestion des membres"));

  fixed49 = gtk_fixed_new ();
  gtk_widget_show (fixed49);
  gtk_container_add (GTK_CONTAINER (Gestion_membres), fixed49);

  label529 = gtk_label_new (_("Gestion des membres"));
  gtk_widget_show (label529);
  gtk_fixed_put (GTK_FIXED (fixed49), label529, 768, 24);
  gtk_widget_set_size_request (label529, 272, 25);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_fixed_put (GTK_FIXED (fixed49), hbuttonbox1, 1272, 528);
  gtk_widget_set_size_request (hbuttonbox1, 300, 29);

  home = gtk_button_new ();
  gtk_widget_show (home);
  gtk_fixed_put (GTK_FIXED (fixed49), home, 1680, 16);
  gtk_widget_set_size_request (home, 72, 48);

  image75 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image75);
  gtk_container_add (GTK_CONTAINER (home), image75);

  statistique = gtk_button_new ();
  gtk_widget_show (statistique);
  gtk_fixed_put (GTK_FIXED (fixed49), statistique, 1472, 16);
  gtk_widget_set_size_request (statistique, 176, 48);

  alignment58 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment58);
  gtk_container_add (GTK_CONTAINER (statistique), alignment58);

  hbox56 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox56);
  gtk_container_add (GTK_CONTAINER (alignment58), hbox56);

  image79 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image79);
  gtk_box_pack_start (GTK_BOX (hbox56), image79, FALSE, FALSE, 0);

  label601 = gtk_label_new_with_mnemonic (_("Statistique"));
  gtk_widget_show (label601);
  gtk_box_pack_start (GTK_BOX (hbox56), label601, FALSE, FALSE, 0);

  histogramme = gtk_button_new ();
  gtk_widget_show (histogramme);
  gtk_fixed_put (GTK_FIXED (fixed49), histogramme, 1288, 16);
  gtk_widget_set_size_request (histogramme, 176, 48);

  alignment59 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment59);
  gtk_container_add (GTK_CONTAINER (histogramme), alignment59);

  hbox57 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox57);
  gtk_container_add (GTK_CONTAINER (alignment59), hbox57);

  image80 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image80);
  gtk_box_pack_start (GTK_BOX (hbox57), image80, FALSE, FALSE, 0);

  label603 = gtk_label_new_with_mnemonic (_("Histogramme"));
  gtk_widget_show (label603);
  gtk_box_pack_start (GTK_BOX (hbox57), label603, FALSE, FALSE, 0);

  gestion = gtk_notebook_new ();
  gtk_widget_show (gestion);
  gtk_fixed_put (GTK_FIXED (fixed49), gestion, 72, 72);
  gtk_widget_set_size_request (gestion, 1720, 776);

  fixed50 = gtk_fixed_new ();
  gtk_widget_show (fixed50);
  gtk_container_add (GTK_CONTAINER (gestion), fixed50);

  fixed54 = gtk_fixed_new ();
  gtk_widget_show (fixed54);
  gtk_fixed_put (GTK_FIXED (fixed50), fixed54, 0, 0);
  gtk_widget_set_size_request (fixed54, 0, 0);

  entrynom = gtk_entry_new ();
  gtk_widget_show (entrynom);
  gtk_fixed_put (GTK_FIXED (fixed50), entrynom, 752, 128);
  gtk_widget_set_size_request (entrynom, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynom), 8226);

  entryprenom = gtk_entry_new ();
  gtk_widget_show (entryprenom);
  gtk_fixed_put (GTK_FIXED (fixed50), entryprenom, 752, 176);
  gtk_widget_set_size_request (entryprenom, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenom), 8226);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed50), entryid, 752, 232);
  gtk_widget_set_size_request (entryid, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  entryemail = gtk_entry_new ();
  gtk_widget_show (entryemail);
  gtk_fixed_put (GTK_FIXED (fixed50), entryemail, 752, 288);
  gtk_widget_set_size_request (entryemail, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemail), 8226);

  entrymdp = gtk_entry_new ();
  gtk_widget_show (entrymdp);
  gtk_fixed_put (GTK_FIXED (fixed50), entrymdp, 752, 336);
  gtk_widget_set_size_request (entrymdp, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp), 8226);

  entrytel = gtk_entry_new ();
  gtk_widget_show (entrytel);
  gtk_fixed_put (GTK_FIXED (fixed50), entrytel, 752, 392);
  gtk_widget_set_size_request (entrytel, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrytel), 8226);

  entryadressee = gtk_entry_new ();
  gtk_widget_show (entryadressee);
  gtk_fixed_put (GTK_FIXED (fixed50), entryadressee, 752, 440);
  gtk_widget_set_size_request (entryadressee, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadressee), 8226);

  jour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (jour1_adj), 1, 0);
  gtk_widget_show (jour1);
  gtk_fixed_put (GTK_FIXED (fixed50), jour1, 800, 496);
  gtk_widget_set_size_request (jour1, 60, 27);

  mois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (mois1_adj), 1, 0);
  gtk_widget_show (mois1);
  gtk_fixed_put (GTK_FIXED (fixed50), mois1, 952, 496);
  gtk_widget_set_size_request (mois1, 60, 27);

  annee1_adj = gtk_adjustment_new (2004, 1970, 2025, 1, 10, 10);
  annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (annee1_adj), 1, 0);
  gtk_widget_show (annee1);
  gtk_fixed_put (GTK_FIXED (fixed50), annee1, 1104, 496);
  gtk_widget_set_size_request (annee1, 60, 27);

  entry122 = gtk_entry_new ();
  gtk_widget_show (entry122);
  gtk_fixed_put (GTK_FIXED (fixed50), entry122, 672, 592);
  gtk_widget_set_size_request (entry122, 184, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry122), 8226);

  label554 = gtk_label_new (_("Ajouter un membre"));
  gtk_widget_show (label554);
  gtk_fixed_put (GTK_FIXED (fixed50), label554, 640, 32);
  gtk_widget_set_size_request (label554, 272, 25);

  annee = gtk_label_new (_("ANNEE"));
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed50), annee, 1040, 504);
  gtk_widget_set_size_request (annee, 57, 17);

  sexe = gtk_label_new (_("Sexe:"));
  gtk_widget_show (sexe);
  gtk_fixed_put (GTK_FIXED (fixed50), sexe, 592, 552);
  gtk_widget_set_size_request (sexe, 0, 0);

  femme = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (femme);
  gtk_fixed_put (GTK_FIXED (fixed50), femme, 664, 544);
  gtk_widget_set_size_request (femme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (femme), femme_group);
  femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (femme));

  homme = gtk_radio_button_new_with_mnemonic (NULL, _("\tHomme"));
  gtk_widget_show (homme);
  gtk_fixed_put (GTK_FIXED (fixed50), homme, 872, 544);
  gtk_widget_set_size_request (homme, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (homme), femme_group);
  femme_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (homme));

  poids = gtk_label_new (_("Poids:"));
  gtk_widget_show (poids);
  gtk_fixed_put (GTK_FIXED (fixed50), poids, 584, 600);
  gtk_widget_set_size_request (poids, 57, 17);

  mois = gtk_label_new (_("MOIS"));
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed50), mois, 880, 504);
  gtk_widget_set_size_request (mois, 72, 16);

  jour = gtk_label_new (_("JOUR"));
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed50), jour, 736, 504);
  gtk_widget_set_size_request (jour, 57, 17);

  prenom = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (prenom);
  gtk_fixed_put (GTK_FIXED (fixed50), prenom, 576, 184);
  gtk_widget_set_size_request (prenom, 88, 17);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed50), ajouter, 1200, 632);
  gtk_widget_set_size_request (ajouter, 144, 53);

  alignment46 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment46);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment46);

  hbox44 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox44);
  gtk_container_add (GTK_CONTAINER (alignment46), hbox44);

  image57 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image57);
  gtk_box_pack_start (GTK_BOX (hbox44), image57, FALSE, FALSE, 0);

  label572 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label572);
  gtk_box_pack_start (GTK_BOX (hbox44), label572, FALSE, FALSE, 0);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed50), annuler, 272, 624);
  gtk_widget_set_size_request (annuler, 154, 53);

  alignment47 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment47);
  gtk_container_add (GTK_CONTAINER (annuler), alignment47);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment47), hbox45);

  image58 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image58);
  gtk_box_pack_start (GTK_BOX (hbox45), image58, FALSE, FALSE, 0);

  label573 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label573);
  gtk_box_pack_start (GTK_BOX (hbox45), label573, FALSE, FALSE, 0);

  message = gtk_label_new (_("message"));
  gtk_widget_show (message);
  gtk_fixed_put (GTK_FIXED (fixed50), message, 592, 696);
  gtk_widget_set_size_request (message, 400, 33);

  nom = gtk_label_new (_("Nom:"));
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed50), nom, 576, 136);
  gtk_widget_set_size_request (nom, 80, 17);

  email = gtk_label_new (_("Email:"));
  gtk_widget_show (email);
  gtk_fixed_put (GTK_FIXED (fixed50), email, 584, 288);
  gtk_widget_set_size_request (email, 72, 17);

  id = gtk_label_new (_("ID:"));
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed50), id, 592, 232);
  gtk_widget_set_size_request (id, 49, 17);

  date = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (date);
  gtk_fixed_put (GTK_FIXED (fixed50), date, 568, 504);
  gtk_widget_set_size_request (date, 144, 17);

  adresse = gtk_label_new (_("Adresse:"));
  gtk_widget_show (adresse);
  gtk_fixed_put (GTK_FIXED (fixed50), adresse, 584, 456);
  gtk_widget_set_size_request (adresse, 100, 17);

  tel = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (tel);
  gtk_fixed_put (GTK_FIXED (fixed50), tel, 584, 400);
  gtk_widget_set_size_request (tel, 100, 17);

  mdp = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (mdp);
  gtk_fixed_put (GTK_FIXED (fixed50), mdp, 576, 344);
  gtk_widget_set_size_request (mdp, 100, 17);
  gtk_misc_set_alignment (GTK_MISC (mdp), 0.45, 0.5);

  image74 = create_pixmap (Gestion_membres, "Blue Yellow Minimalist Running Sport Logo.png");
  gtk_widget_show (image74);
  gtk_fixed_put (GTK_FIXED (fixed50), image74, 1136, 112);
  gtk_widget_set_size_request (image74, 336, 309);

  ajouterb = gtk_label_new (_("Ajouter"));
  gtk_widget_show (ajouterb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (gestion), gtk_notebook_get_nth_page (GTK_NOTEBOOK (gestion), 0), ajouterb);

  fixed51 = gtk_fixed_new ();
  gtk_widget_show (fixed51);
  gtk_container_add (GTK_CONTAINER (gestion), fixed51);

  entryId = gtk_entry_new ();
  gtk_widget_show (entryId);
  gtk_fixed_put (GTK_FIXED (fixed51), entryId, 672, 120);
  gtk_widget_set_size_request (entryId, 232, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryId), 8226);

  entrynomn = gtk_entry_new ();
  gtk_widget_show (entrynomn);
  gtk_fixed_put (GTK_FIXED (fixed51), entrynomn, 688, 200);
  gtk_widget_set_size_request (entrynomn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomn), 8226);

  entryprenomn = gtk_entry_new ();
  gtk_widget_show (entryprenomn);
  gtk_fixed_put (GTK_FIXED (fixed51), entryprenomn, 688, 248);
  gtk_widget_set_size_request (entryprenomn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomn), 8226);

  entryidn = gtk_entry_new ();
  gtk_widget_show (entryidn);
  gtk_fixed_put (GTK_FIXED (fixed51), entryidn, 680, 296);
  gtk_widget_set_size_request (entryidn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidn), 8226);

  entryemailn = gtk_entry_new ();
  gtk_widget_show (entryemailn);
  gtk_fixed_put (GTK_FIXED (fixed51), entryemailn, 680, 344);
  gtk_widget_set_size_request (entryemailn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryemailn), 8226);

  entrymdpn = gtk_entry_new ();
  gtk_widget_show (entrymdpn);
  gtk_fixed_put (GTK_FIXED (fixed51), entrymdpn, 696, 400);
  gtk_widget_set_size_request (entrymdpn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdpn), 8226);

  entryteln = gtk_entry_new ();
  gtk_widget_show (entryteln);
  gtk_fixed_put (GTK_FIXED (fixed51), entryteln, 688, 448);
  gtk_widget_set_size_request (entryteln, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryteln), 8226);

  entryadressen = gtk_entry_new ();
  gtk_widget_show (entryadressen);
  gtk_fixed_put (GTK_FIXED (fixed51), entryadressen, 680, 496);
  gtk_widget_set_size_request (entryadressen, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryadressen), 8226);

  nouvjour1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nouvjour1 = gtk_spin_button_new (GTK_ADJUSTMENT (nouvjour1_adj), 1, 0);
  gtk_widget_show (nouvjour1);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvjour1, 808, 552);
  gtk_widget_set_size_request (nouvjour1, 60, 27);

  nouvmois1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nouvmois1 = gtk_spin_button_new (GTK_ADJUSTMENT (nouvmois1_adj), 1, 0);
  gtk_widget_show (nouvmois1);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvmois1, 960, 552);
  gtk_widget_set_size_request (nouvmois1, 60, 27);

  nouvannee1_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  nouvannee1 = gtk_spin_button_new (GTK_ADJUSTMENT (nouvannee1_adj), 1, 0);
  gtk_widget_show (nouvannee1);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvannee1, 1120, 552);
  gtk_widget_set_size_request (nouvannee1, 60, 27);

  entrypoidsn = gtk_entry_new ();
  gtk_widget_show (entrypoidsn);
  gtk_fixed_put (GTK_FIXED (fixed51), entrypoidsn, 656, 648);
  gtk_widget_set_size_request (entrypoidsn, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrypoidsn), 8226);

  radiobutton46 = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobutton46);
  gtk_fixed_put (GTK_FIXED (fixed51), radiobutton46, 688, 600);
  gtk_widget_set_size_request (radiobutton46, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton46), radiobutton46_group);
  radiobutton46_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton46));

  radiobutton47 = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobutton47);
  gtk_fixed_put (GTK_FIXED (fixed51), radiobutton47, 864, 600);
  gtk_widget_set_size_request (radiobutton47, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton47), radiobutton46_group);
  radiobutton46_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton47));

  label555 = gtk_label_new (_("Modifier un membre"));
  gtk_widget_show (label555);
  gtk_fixed_put (GTK_FIXED (fixed51), label555, 672, 48);
  gtk_widget_set_size_request (label555, 256, 33);

  nouvprenom = gtk_label_new (_("Pr\303\251nom:"));
  gtk_widget_show (nouvprenom);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvprenom, 576, 256);
  gtk_widget_set_size_request (nouvprenom, 88, 17);

  nouvnom = gtk_label_new (_("Nom:"));
  gtk_widget_show (nouvnom);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvnom, 576, 208);
  gtk_widget_set_size_request (nouvnom, 80, 17);

  nouvmois = gtk_label_new (_("MOIS"));
  gtk_widget_show (nouvmois);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvmois, 880, 560);
  gtk_widget_set_size_request (nouvmois, 72, 16);

  nouvannee = gtk_label_new (_("ANNEE"));
  gtk_widget_show (nouvannee);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvannee, 1040, 560);
  gtk_widget_set_size_request (nouvannee, 57, 17);

  nouvsexe = gtk_label_new (_("Sexe:"));
  gtk_widget_show (nouvsexe);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvsexe, 592, 608);
  gtk_widget_set_size_request (nouvsexe, 0, 0);

  nouvpoids = gtk_label_new (_("Poids:"));
  gtk_widget_show (nouvpoids);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvpoids, 584, 656);
  gtk_widget_set_size_request (nouvpoids, 57, 17);

  nouvjour = gtk_label_new (_("JOUR"));
  gtk_widget_show (nouvjour);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvjour, 736, 560);
  gtk_widget_set_size_request (nouvjour, 57, 17);

  Id = gtk_label_new (_("ID:"));
  gtk_widget_show (Id);
  gtk_fixed_put (GTK_FIXED (fixed51), Id, 584, 136);
  gtk_widget_set_size_request (Id, 57, 17);

  nouvid = gtk_label_new (_("ID:"));
  gtk_widget_show (nouvid);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvid, 592, 304);
  gtk_widget_set_size_request (nouvid, 49, 17);

  chercher = gtk_button_new ();
  gtk_widget_show (chercher);
  gtk_fixed_put (GTK_FIXED (fixed51), chercher, 968, 120);
  gtk_widget_set_size_request (chercher, 56, 40);

  image64 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image64);
  gtk_container_add (GTK_CONTAINER (chercher), image64);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed51), modifier, 1152, 672);
  gtk_widget_set_size_request (modifier, 154, 53);

  alignment48 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment48);
  gtk_container_add (GTK_CONTAINER (modifier), alignment48);

  hbox46 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox46);
  gtk_container_add (GTK_CONTAINER (alignment48), hbox46);

  image59 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox46), image59, FALSE, FALSE, 0);

  label574 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label574);
  gtk_box_pack_start (GTK_BOX (hbox46), label574, FALSE, FALSE, 0);

  annulern = gtk_button_new ();
  gtk_widget_show (annulern);
  gtk_fixed_put (GTK_FIXED (fixed51), annulern, 272, 672);
  gtk_widget_set_size_request (annulern, 162, 53);

  alignment49 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment49);
  gtk_container_add (GTK_CONTAINER (annulern), alignment49);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment49), hbox47);

  image60 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image60);
  gtk_box_pack_start (GTK_BOX (hbox47), image60, FALSE, FALSE, 0);

  label575 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label575);
  gtk_box_pack_start (GTK_BOX (hbox47), label575, FALSE, FALSE, 0);

  nouvemail = gtk_label_new (_("Email:"));
  gtk_widget_show (nouvemail);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvemail, 584, 352);
  gtk_widget_set_size_request (nouvemail, 72, 17);

  nouvmdp = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (nouvmdp);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvmdp, 576, 408);
  gtk_widget_set_size_request (nouvmdp, 100, 17);

  nouvtel = gtk_label_new (_("T\303\251l\303\251phone:"));
  gtk_widget_show (nouvtel);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvtel, 584, 456);
  gtk_widget_set_size_request (nouvtel, 100, 17);

  nouvadresse = gtk_label_new (_("Adresse:"));
  gtk_widget_show (nouvadresse);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvadresse, 584, 504);
  gtk_widget_set_size_request (nouvadresse, 100, 17);

  nouvdate = gtk_label_new (_("Date de naissance:"));
  gtk_widget_show (nouvdate);
  gtk_fixed_put (GTK_FIXED (fixed51), nouvdate, 568, 560);
  gtk_widget_set_size_request (nouvdate, 100, 17);

  message2 = gtk_label_new ("");
  gtk_widget_show (message2);
  gtk_fixed_put (GTK_FIXED (fixed51), message2, 528, 688);
  gtk_widget_set_size_request (message2, 536, 33);

  modifierb = gtk_label_new (_("Modifier"));
  gtk_widget_show (modifierb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (gestion), gtk_notebook_get_nth_page (GTK_NOTEBOOK (gestion), 1), modifierb);

  fixed53 = gtk_fixed_new ();
  gtk_widget_show (fixed53);
  gtk_container_add (GTK_CONTAINER (gestion), fixed53);

  label579 = gtk_label_new (_("Chercher un membre"));
  gtk_widget_show (label579);
  gtk_fixed_put (GTK_FIXED (fixed53), label579, 680, 56);
  gtk_widget_set_size_request (label579, 192, 41);

  entryidd = gtk_entry_new ();
  gtk_widget_show (entryidd);
  gtk_fixed_put (GTK_FIXED (fixed53), entryidd, 640, 184);
  gtk_widget_set_size_request (entryidd, 264, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidd), 8226);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed53), treeview4, 344, 296);
  gtk_widget_set_size_request (treeview4, 952, 328);

  idd = gtk_label_new (_("ID:"));
  gtk_widget_show (idd);
  gtk_fixed_put (GTK_FIXED (fixed53), idd, 552, 192);
  gtk_widget_set_size_request (idd, 57, 17);

  recherche = gtk_button_new ();
  gtk_widget_show (recherche);
  gtk_fixed_put (GTK_FIXED (fixed53), recherche, 976, 176);
  gtk_widget_set_size_request (recherche, 64, 40);

  alignment52 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment52);
  gtk_container_add (GTK_CONTAINER (recherche), alignment52);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment52), hbox50);

  image63 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image63);
  gtk_box_pack_start (GTK_BOX (hbox50), image63, FALSE, FALSE, 0);

  label580 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label580);
  gtk_box_pack_start (GTK_BOX (hbox50), label580, FALSE, FALSE, 0);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed53), afficher, 1088, 176);
  gtk_widget_set_size_request (afficher, 104, 37);

  alignment53 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment53);
  gtk_container_add (GTK_CONTAINER (afficher), alignment53);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment53), hbox51);

  image66 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image66);
  gtk_box_pack_start (GTK_BOX (hbox51), image66, FALSE, FALSE, 0);

  label581 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label581);
  gtk_box_pack_start (GTK_BOX (hbox51), label581, FALSE, FALSE, 0);

  label582 = gtk_label_new (_("Clickez ici pour afficher \ntous les membres"));
  gtk_widget_show (label582);
  gtk_fixed_put (GTK_FIXED (fixed53), label582, 1008, 128);
  gtk_widget_set_size_request (label582, 312, 48);

  label583 = gtk_label_new (_("Si vous voulez supprimer un membre, \ndouble clickez sur la ligne"));
  gtk_widget_show (label583);
  gtk_fixed_put (GTK_FIXED (fixed53), label583, 992, 640);
  gtk_widget_set_size_request (label583, 336, 40);

  chercherb = gtk_label_new (_("Chercher et supprimer"));
  gtk_widget_show (chercherb);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (gestion), gtk_notebook_get_nth_page (GTK_NOTEBOOK (gestion), 2), chercherb);

  g_signal_connect ((gpointer) home, "clicked",
                    G_CALLBACK (on_home_clicked),
                    NULL);
  g_signal_connect ((gpointer) statistique, "clicked",
                    G_CALLBACK (on_statistique_clicked),
                    NULL);
  g_signal_connect ((gpointer) histogramme, "clicked",
                    G_CALLBACK (on_histogramme_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);
  g_signal_connect ((gpointer) chercher, "clicked",
                    G_CALLBACK (on_chercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) annulern, "clicked",
                    G_CALLBACK (on_annulern_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview4, "row_activated",
                    G_CALLBACK (on_treeview4_row_activated),
                    NULL);
  g_signal_connect ((gpointer) recherche, "clicked",
                    G_CALLBACK (on_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_membres, Gestion_membres, "Gestion_membres");
  GLADE_HOOKUP_OBJECT (Gestion_membres, fixed49, "fixed49");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label529, "label529");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, home, "home");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image75, "image75");
  GLADE_HOOKUP_OBJECT (Gestion_membres, statistique, "statistique");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment58, "alignment58");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox56, "hbox56");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image79, "image79");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label601, "label601");
  GLADE_HOOKUP_OBJECT (Gestion_membres, histogramme, "histogramme");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment59, "alignment59");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox57, "hbox57");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image80, "image80");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label603, "label603");
  GLADE_HOOKUP_OBJECT (Gestion_membres, gestion, "gestion");
  GLADE_HOOKUP_OBJECT (Gestion_membres, fixed50, "fixed50");
  GLADE_HOOKUP_OBJECT (Gestion_membres, fixed54, "fixed54");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrynom, "entrynom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryprenom, "entryprenom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryemail, "entryemail");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrymdp, "entrymdp");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrytel, "entrytel");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryadressee, "entryadressee");
  GLADE_HOOKUP_OBJECT (Gestion_membres, jour1, "jour1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, mois1, "mois1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, annee1, "annee1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entry122, "entry122");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label554, "label554");
  GLADE_HOOKUP_OBJECT (Gestion_membres, annee, "annee");
  GLADE_HOOKUP_OBJECT (Gestion_membres, sexe, "sexe");
  GLADE_HOOKUP_OBJECT (Gestion_membres, femme, "femme");
  GLADE_HOOKUP_OBJECT (Gestion_membres, homme, "homme");
  GLADE_HOOKUP_OBJECT (Gestion_membres, poids, "poids");
  GLADE_HOOKUP_OBJECT (Gestion_membres, mois, "mois");
  GLADE_HOOKUP_OBJECT (Gestion_membres, jour, "jour");
  GLADE_HOOKUP_OBJECT (Gestion_membres, prenom, "prenom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image57, "image57");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label572, "label572");
  GLADE_HOOKUP_OBJECT (Gestion_membres, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment47, "alignment47");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image58, "image58");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label573, "label573");
  GLADE_HOOKUP_OBJECT (Gestion_membres, message, "message");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nom, "nom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, email, "email");
  GLADE_HOOKUP_OBJECT (Gestion_membres, id, "id");
  GLADE_HOOKUP_OBJECT (Gestion_membres, date, "date");
  GLADE_HOOKUP_OBJECT (Gestion_membres, adresse, "adresse");
  GLADE_HOOKUP_OBJECT (Gestion_membres, tel, "tel");
  GLADE_HOOKUP_OBJECT (Gestion_membres, mdp, "mdp");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image74, "image74");
  GLADE_HOOKUP_OBJECT (Gestion_membres, ajouterb, "ajouterb");
  GLADE_HOOKUP_OBJECT (Gestion_membres, fixed51, "fixed51");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryId, "entryId");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrynomn, "entrynomn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryprenomn, "entryprenomn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryidn, "entryidn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryemailn, "entryemailn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrymdpn, "entrymdpn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryteln, "entryteln");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryadressen, "entryadressen");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvjour1, "nouvjour1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvmois1, "nouvmois1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvannee1, "nouvannee1");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entrypoidsn, "entrypoidsn");
  GLADE_HOOKUP_OBJECT (Gestion_membres, radiobutton46, "radiobutton46");
  GLADE_HOOKUP_OBJECT (Gestion_membres, radiobutton47, "radiobutton47");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label555, "label555");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvprenom, "nouvprenom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvnom, "nouvnom");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvmois, "nouvmois");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvannee, "nouvannee");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvsexe, "nouvsexe");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvpoids, "nouvpoids");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvjour, "nouvjour");
  GLADE_HOOKUP_OBJECT (Gestion_membres, Id, "Id");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvid, "nouvid");
  GLADE_HOOKUP_OBJECT (Gestion_membres, chercher, "chercher");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image64, "image64");
  GLADE_HOOKUP_OBJECT (Gestion_membres, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment48, "alignment48");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image59, "image59");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label574, "label574");
  GLADE_HOOKUP_OBJECT (Gestion_membres, annulern, "annulern");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment49, "alignment49");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image60, "image60");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label575, "label575");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvemail, "nouvemail");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvmdp, "nouvmdp");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvtel, "nouvtel");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvadresse, "nouvadresse");
  GLADE_HOOKUP_OBJECT (Gestion_membres, nouvdate, "nouvdate");
  GLADE_HOOKUP_OBJECT (Gestion_membres, message2, "message2");
  GLADE_HOOKUP_OBJECT (Gestion_membres, modifierb, "modifierb");
  GLADE_HOOKUP_OBJECT (Gestion_membres, fixed53, "fixed53");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label579, "label579");
  GLADE_HOOKUP_OBJECT (Gestion_membres, entryidd, "entryidd");
  GLADE_HOOKUP_OBJECT (Gestion_membres, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (Gestion_membres, idd, "idd");
  GLADE_HOOKUP_OBJECT (Gestion_membres, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment52, "alignment52");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image63, "image63");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label580, "label580");
  GLADE_HOOKUP_OBJECT (Gestion_membres, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (Gestion_membres, alignment53, "alignment53");
  GLADE_HOOKUP_OBJECT (Gestion_membres, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (Gestion_membres, image66, "image66");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label581, "label581");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label582, "label582");
  GLADE_HOOKUP_OBJECT (Gestion_membres, label583, "label583");
  GLADE_HOOKUP_OBJECT (Gestion_membres, chercherb, "chercherb");

  return Gestion_membres;
}

GtkWidget*
create_demande_coach (void)
{
  GtkWidget *demande_coach;
  GtkWidget *fixed55;
  GtkWidget *image73;
  GtkWidget *fixed56;
  GtkWidget *entryidcoach;
  GtkWidget *label588;
  GtkWidget *reserver;
  GtkWidget *alignment54;
  GtkWidget *hbox52;
  GtkWidget *image67;
  GtkWidget *label589;
  GtkWidget *voir;
  GtkWidget *alignment55;
  GtkWidget *hbox53;
  GtkWidget *image68;
  GtkWidget *label590;
  GtkWidget *label587;
  GtkWidget *label586;
  GtkWidget *checkbuttonperte;
  GtkWidget *checkbuttonreeduction;
  GtkWidget *checkbuttonprise;
  GtkWidget *checkbuttongymnastique;
  GtkWidget *checkbuttonamelioration;
  GtkWidget *label584;
  GtkWidget *label585;
  GtkWidget *combobox1;
  GtkWidget *checkbuttonmardi;
  GtkWidget *checkbuttonlundi;
  GtkWidget *checkbuttonjeudi;
  GtkWidget *checkbuttonmercredi;
  GtkWidget *checkbuttonvendredi;
  GtkWidget *sortie;
  GtkWidget *image72;
  GtkWidget *home2;
  GtkWidget *image76;

  demande_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (demande_coach, 1900, 1000);
  gtk_window_set_title (GTK_WINDOW (demande_coach), _("demande coach"));

  fixed55 = gtk_fixed_new ();
  gtk_widget_show (fixed55);
  gtk_container_add (GTK_CONTAINER (demande_coach), fixed55);

  image73 = create_pixmap (demande_coach, "coach2.jpeg");
  gtk_widget_show (image73);
  gtk_fixed_put (GTK_FIXED (fixed55), image73, 1024, 440);
  gtk_widget_set_size_request (image73, 472, 189);

  fixed56 = gtk_fixed_new ();
  gtk_widget_show (fixed56);
  gtk_fixed_put (GTK_FIXED (fixed55), fixed56, 8, 0);
  gtk_widget_set_size_request (fixed56, 0, 0);

  entryidcoach = gtk_entry_new ();
  gtk_widget_show (entryidcoach);
  gtk_fixed_put (GTK_FIXED (fixed56), entryidcoach, 664, 224);
  gtk_widget_set_size_request (entryidcoach, 248, 43);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidcoach), 8226);

  label588 = gtk_label_new (_("ID:"));
  gtk_widget_show (label588);
  gtk_fixed_put (GTK_FIXED (fixed56), label588, 528, 240);
  gtk_widget_set_size_request (label588, 57, 17);

  reserver = gtk_button_new ();
  gtk_widget_show (reserver);
  gtk_fixed_put (GTK_FIXED (fixed56), reserver, 1192, 728);
  gtk_widget_set_size_request (reserver, 176, 61);

  alignment54 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment54);
  gtk_container_add (GTK_CONTAINER (reserver), alignment54);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment54), hbox52);

  image67 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox52), image67, FALSE, FALSE, 0);

  label589 = gtk_label_new_with_mnemonic (_("R\303\251server"));
  gtk_widget_show (label589);
  gtk_box_pack_start (GTK_BOX (hbox52), label589, FALSE, FALSE, 0);

  voir = gtk_button_new ();
  gtk_widget_show (voir);
  gtk_fixed_put (GTK_FIXED (fixed56), voir, 1392, 728);
  gtk_widget_set_size_request (voir, 184, 56);

  alignment55 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment55);
  gtk_container_add (GTK_CONTAINER (voir), alignment55);

  hbox53 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox53);
  gtk_container_add (GTK_CONTAINER (alignment55), hbox53);

  image68 = gtk_image_new_from_stock ("gtk-media-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_box_pack_start (GTK_BOX (hbox53), image68, FALSE, FALSE, 0);

  label590 = gtk_label_new_with_mnemonic (_("voir mes reservations"));
  gtk_widget_show (label590);
  gtk_box_pack_start (GTK_BOX (hbox53), label590, FALSE, FALSE, 0);

  label587 = gtk_label_new (_("Demande d'un coach priv\303\251"));
  gtk_widget_show (label587);
  gtk_fixed_put (GTK_FIXED (fixed56), label587, 648, 56);
  gtk_widget_set_size_request (label587, 336, 57);

  label586 = gtk_label_new (_("Objectif de coaching"));
  gtk_widget_show (label586);
  gtk_fixed_put (GTK_FIXED (fixed56), label586, 8, 368);
  gtk_widget_set_size_request (label586, 200, 33);

  checkbuttonperte = gtk_check_button_new_with_mnemonic (_("Cardio"));
  gtk_widget_show (checkbuttonperte);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonperte, 280, 368);
  gtk_widget_set_size_request (checkbuttonperte, 136, 24);

  checkbuttonreeduction = gtk_check_button_new_with_mnemonic (_("Musculation"));
  gtk_widget_show (checkbuttonreeduction);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonreeduction, 568, 360);
  gtk_widget_set_size_request (checkbuttonreeduction, 216, 32);

  checkbuttonprise = gtk_check_button_new_with_mnemonic (_("Dance"));
  gtk_widget_show (checkbuttonprise);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonprise, 408, 360);
  gtk_widget_set_size_request (checkbuttonprise, 136, 32);

  checkbuttongymnastique = gtk_check_button_new_with_mnemonic (_("Gymnastique"));
  gtk_widget_show (checkbuttongymnastique);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttongymnastique, 904, 360);
  gtk_widget_set_size_request (checkbuttongymnastique, 118, 24);

  checkbuttonamelioration = gtk_check_button_new_with_mnemonic (_("Kick boxing"));
  gtk_widget_show (checkbuttonamelioration);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonamelioration, 728, 360);
  gtk_widget_set_size_request (checkbuttonamelioration, 256, 32);

  label584 = gtk_label_new (_("Les jours d'entrainement:"));
  gtk_widget_show (label584);
  gtk_fixed_put (GTK_FIXED (fixed56), label584, 32, 544);
  gtk_widget_set_size_request (label584, 192, 33);

  label585 = gtk_label_new (_("Disponibilit\303\251:"));
  gtk_widget_show (label585);
  gtk_fixed_put (GTK_FIXED (fixed56), label585, 24, 464);
  gtk_widget_set_size_request (label585, 136, 25);

  combobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1);
  gtk_fixed_put (GTK_FIXED (fixed56), combobox1, 168, 456);
  gtk_widget_set_size_request (combobox1, 200, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Matin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Midi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1), _("Soir"));

  checkbuttonmardi = gtk_check_button_new_with_mnemonic (_("MARDI"));
  gtk_widget_show (checkbuttonmardi);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonmardi, 360, 544);
  gtk_widget_set_size_request (checkbuttonmardi, 118, 24);

  checkbuttonlundi = gtk_check_button_new_with_mnemonic (_("LUNDI"));
  gtk_widget_show (checkbuttonlundi);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonlundi, 240, 544);
  gtk_widget_set_size_request (checkbuttonlundi, 118, 24);

  checkbuttonjeudi = gtk_check_button_new_with_mnemonic (_("JEUDI"));
  gtk_widget_show (checkbuttonjeudi);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonjeudi, 600, 544);
  gtk_widget_set_size_request (checkbuttonjeudi, 118, 24);

  checkbuttonmercredi = gtk_check_button_new_with_mnemonic (_("MERCREDI"));
  gtk_widget_show (checkbuttonmercredi);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonmercredi, 472, 544);
  gtk_widget_set_size_request (checkbuttonmercredi, 118, 24);

  checkbuttonvendredi = gtk_check_button_new_with_mnemonic (_("VENDREDI"));
  gtk_widget_show (checkbuttonvendredi);
  gtk_fixed_put (GTK_FIXED (fixed56), checkbuttonvendredi, 704, 544);
  gtk_widget_set_size_request (checkbuttonvendredi, 126, 24);

  sortie = gtk_label_new (_("resultat:"));
  gtk_widget_show (sortie);
  gtk_fixed_put (GTK_FIXED (fixed56), sortie, 0, 704);
  gtk_widget_set_size_request (sortie, 392, 41);

  image72 = create_pixmap (demande_coach, "coach.jpeg");
  gtk_widget_show (image72);
  gtk_fixed_put (GTK_FIXED (fixed56), image72, 120, 40);
  gtk_widget_set_size_request (image72, 376, 173);

  home2 = gtk_button_new ();
  gtk_widget_show (home2);
  gtk_fixed_put (GTK_FIXED (fixed56), home2, 1288, 40);
  gtk_widget_set_size_request (home2, 72, 48);

  image76 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image76);
  gtk_container_add (GTK_CONTAINER (home2), image76);

  g_signal_connect ((gpointer) reserver, "clicked",
                    G_CALLBACK (on_reserver_clicked),
                    NULL);
  g_signal_connect ((gpointer) voir, "clicked",
                    G_CALLBACK (on_voir_clicked),
                    NULL);
  g_signal_connect ((gpointer) home2, "clicked",
                    G_CALLBACK (on_home2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (demande_coach, demande_coach, "demande_coach");
  GLADE_HOOKUP_OBJECT (demande_coach, fixed55, "fixed55");
  GLADE_HOOKUP_OBJECT (demande_coach, image73, "image73");
  GLADE_HOOKUP_OBJECT (demande_coach, fixed56, "fixed56");
  GLADE_HOOKUP_OBJECT (demande_coach, entryidcoach, "entryidcoach");
  GLADE_HOOKUP_OBJECT (demande_coach, label588, "label588");
  GLADE_HOOKUP_OBJECT (demande_coach, reserver, "reserver");
  GLADE_HOOKUP_OBJECT (demande_coach, alignment54, "alignment54");
  GLADE_HOOKUP_OBJECT (demande_coach, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (demande_coach, image67, "image67");
  GLADE_HOOKUP_OBJECT (demande_coach, label589, "label589");
  GLADE_HOOKUP_OBJECT (demande_coach, voir, "voir");
  GLADE_HOOKUP_OBJECT (demande_coach, alignment55, "alignment55");
  GLADE_HOOKUP_OBJECT (demande_coach, hbox53, "hbox53");
  GLADE_HOOKUP_OBJECT (demande_coach, image68, "image68");
  GLADE_HOOKUP_OBJECT (demande_coach, label590, "label590");
  GLADE_HOOKUP_OBJECT (demande_coach, label587, "label587");
  GLADE_HOOKUP_OBJECT (demande_coach, label586, "label586");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonperte, "checkbuttonperte");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonreeduction, "checkbuttonreeduction");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonprise, "checkbuttonprise");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttongymnastique, "checkbuttongymnastique");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonamelioration, "checkbuttonamelioration");
  GLADE_HOOKUP_OBJECT (demande_coach, label584, "label584");
  GLADE_HOOKUP_OBJECT (demande_coach, label585, "label585");
  GLADE_HOOKUP_OBJECT (demande_coach, combobox1, "combobox1");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonmardi, "checkbuttonmardi");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonlundi, "checkbuttonlundi");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonjeudi, "checkbuttonjeudi");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonmercredi, "checkbuttonmercredi");
  GLADE_HOOKUP_OBJECT (demande_coach, checkbuttonvendredi, "checkbuttonvendredi");
  GLADE_HOOKUP_OBJECT (demande_coach, sortie, "sortie");
  GLADE_HOOKUP_OBJECT (demande_coach, image72, "image72");
  GLADE_HOOKUP_OBJECT (demande_coach, home2, "home2");
  GLADE_HOOKUP_OBJECT (demande_coach, image76, "image76");

  return demande_coach;
}

GtkWidget*
create_reservation (void)
{
  GtkWidget *reservation;
  GtkWidget *fixed57;
  GtkWidget *treeview5;
  GtkWidget *affiche;
  GtkWidget *retour;
  GtkWidget *alignment56;
  GtkWidget *hbox54;
  GtkWidget *image69;
  GtkWidget *label592;
  GtkWidget *label600;
  GtkWidget *label591;

  reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reservation), _("reservation"));

  fixed57 = gtk_fixed_new ();
  gtk_widget_show (fixed57);
  gtk_container_add (GTK_CONTAINER (reservation), fixed57);

  treeview5 = gtk_tree_view_new ();
  gtk_widget_show (treeview5);
  gtk_fixed_put (GTK_FIXED (fixed57), treeview5, 208, 264);
  gtk_widget_set_size_request (treeview5, 1352, 288);

  affiche = gtk_button_new_with_mnemonic (_("Afficher les reservations"));
  gtk_widget_show (affiche);
  gtk_fixed_put (GTK_FIXED (fixed57), affiche, 648, 192);
  gtk_widget_set_size_request (affiche, 440, 37);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed57), retour, 160, 744);
  gtk_widget_set_size_request (retour, 352, 69);

  alignment56 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment56);
  gtk_container_add (GTK_CONTAINER (retour), alignment56);

  hbox54 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox54);
  gtk_container_add (GTK_CONTAINER (alignment56), hbox54);

  image69 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image69);
  gtk_box_pack_start (GTK_BOX (hbox54), image69, FALSE, FALSE, 0);

  label592 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label592);
  gtk_box_pack_start (GTK_BOX (hbox54), label592, FALSE, FALSE, 0);

  label600 = gtk_label_new (_("Si vous voulez modifier,\n clickez une seule fois et modier d'apres le tableau"));
  gtk_widget_show (label600);
  gtk_fixed_put (GTK_FIXED (fixed57), label600, 696, 632);
  gtk_widget_set_size_request (label600, 352, 41);

  label591 = gtk_label_new (_("Si vous voulez supprimer une r\303\251servation, double clickez!"));
  gtk_widget_show (label591);
  gtk_fixed_put (GTK_FIXED (fixed57), label591, 576, 552);
  gtk_widget_set_size_request (label591, 624, 81);

  g_signal_connect ((gpointer) treeview5, "row_activated",
                    G_CALLBACK (on_treeview5_row_activated),
                    NULL);
  g_signal_connect ((gpointer) affiche, "clicked",
                    G_CALLBACK (on_affiche_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reservation, reservation, "reservation");
  GLADE_HOOKUP_OBJECT (reservation, fixed57, "fixed57");
  GLADE_HOOKUP_OBJECT (reservation, treeview5, "treeview5");
  GLADE_HOOKUP_OBJECT (reservation, affiche, "affiche");
  GLADE_HOOKUP_OBJECT (reservation, retour, "retour");
  GLADE_HOOKUP_OBJECT (reservation, alignment56, "alignment56");
  GLADE_HOOKUP_OBJECT (reservation, hbox54, "hbox54");
  GLADE_HOOKUP_OBJECT (reservation, image69, "image69");
  GLADE_HOOKUP_OBJECT (reservation, label592, "label592");
  GLADE_HOOKUP_OBJECT (reservation, label600, "label600");
  GLADE_HOOKUP_OBJECT (reservation, label591, "label591");

  return reservation;
}

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed58;
  GtkWidget *entry20;
  GtkWidget *label593;
  GtkWidget *entry21;
  GtkWidget *label594;
  GtkWidget *label595;
  GtkWidget *label596;
  GtkWidget *valider;
  GtkWidget *alignment57;
  GtkWidget *hbox55;
  GtkWidget *image71;
  GtkWidget *label597;
  GtkWidget *label55;
  GtkWidget *image70;
  GtkWidget *eye_auth;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification), _("authentification"));

  fixed58 = gtk_fixed_new ();
  gtk_widget_show (fixed58);
  gtk_container_add (GTK_CONTAINER (authentification), fixed58);

  entry20 = gtk_entry_new ();
  gtk_widget_show (entry20);
  gtk_fixed_put (GTK_FIXED (fixed58), entry20, 776, 448);
  gtk_widget_set_size_request (entry20, 240, 40);
  gtk_entry_set_visibility (GTK_ENTRY (entry20), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry20), 8226);

  label593 = gtk_label_new ("");
  gtk_widget_show (label593);
  gtk_fixed_put (GTK_FIXED (fixed58), label593, 56, 256);
  gtk_widget_set_size_request (label593, 57, 17);

  entry21 = gtk_entry_new ();
  gtk_widget_show (entry21);
  gtk_fixed_put (GTK_FIXED (fixed58), entry21, 760, 384);
  gtk_widget_set_size_request (entry21, 264, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry21), 8226);

  label594 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label594);
  gtk_fixed_put (GTK_FIXED (fixed58), label594, 464, 352);
  gtk_widget_set_size_request (label594, 168, 32);

  label595 = gtk_label_new (_("Veuillez-vous entrer votre:"));
  gtk_widget_show (label595);
  gtk_fixed_put (GTK_FIXED (fixed58), label595, 440, 296);
  gtk_widget_set_size_request (label595, 320, 33);

  label596 = gtk_label_new (_("Mot de passe:"));
  gtk_widget_show (label596);
  gtk_fixed_put (GTK_FIXED (fixed58), label596, 480, 488);
  gtk_widget_set_size_request (label596, 160, 25);

  valider = gtk_button_new ();
  gtk_widget_show (valider);
  gtk_fixed_put (GTK_FIXED (fixed58), valider, 800, 752);
  gtk_widget_set_size_request (valider, 162, 61);

  alignment57 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment57);
  gtk_container_add (GTK_CONTAINER (valider), alignment57);

  hbox55 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox55);
  gtk_container_add (GTK_CONTAINER (alignment57), hbox55);

  image71 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image71);
  gtk_box_pack_start (GTK_BOX (hbox55), image71, FALSE, FALSE, 0);

  label597 = gtk_label_new_with_mnemonic (_("VALIDER"));
  gtk_widget_show (label597);
  gtk_box_pack_start (GTK_BOX (hbox55), label597, FALSE, FALSE, 0);

  label55 = gtk_label_new ("");
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed58), label55, 888, 840);
  gtk_widget_set_size_request (label55, 57, 17);

  image70 = create_pixmap (authentification, "bien.jpg");
  gtk_widget_show (image70);
  gtk_fixed_put (GTK_FIXED (fixed58), image70, 0, 0);
  gtk_widget_set_size_request (image70, 1760, 760);

  eye_auth = gtk_button_new_with_mnemonic (_("\360\237\221\201"));
  gtk_widget_show (eye_auth);
  gtk_fixed_put (GTK_FIXED (fixed58), eye_auth, 1040, 456);
  gtk_widget_set_size_request (eye_auth, 40, 29);

  g_signal_connect ((gpointer) valider, "clicked",
                    G_CALLBACK (on_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) eye_auth, "clicked",
                    G_CALLBACK (on_eye_auth_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed58, "fixed58");
  GLADE_HOOKUP_OBJECT (authentification, entry20, "entry20");
  GLADE_HOOKUP_OBJECT (authentification, label593, "label593");
  GLADE_HOOKUP_OBJECT (authentification, entry21, "entry21");
  GLADE_HOOKUP_OBJECT (authentification, label594, "label594");
  GLADE_HOOKUP_OBJECT (authentification, label595, "label595");
  GLADE_HOOKUP_OBJECT (authentification, label596, "label596");
  GLADE_HOOKUP_OBJECT (authentification, valider, "valider");
  GLADE_HOOKUP_OBJECT (authentification, alignment57, "alignment57");
  GLADE_HOOKUP_OBJECT (authentification, hbox55, "hbox55");
  GLADE_HOOKUP_OBJECT (authentification, image71, "image71");
  GLADE_HOOKUP_OBJECT (authentification, label597, "label597");
  GLADE_HOOKUP_OBJECT (authentification, label55, "label55");
  GLADE_HOOKUP_OBJECT (authentification, image70, "image70");
  GLADE_HOOKUP_OBJECT (authentification, eye_auth, "eye_auth");

  return authentification;
}

GtkWidget*
create_acceuiladmin (void)
{
  GtkWidget *acceuiladmin;
  GtkWidget *fixed59;
  GtkWidget *centre;
  GtkWidget *evenement;
  GtkWidget *equipement;
  GtkWidget *label598;
  GtkWidget *membre;
  GtkWidget *entraineur;
  GtkWidget *cours;
  GtkWidget *home3;
  GtkWidget *image77;

  acceuiladmin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuiladmin), _("acceuiladmin"));

  fixed59 = gtk_fixed_new ();
  gtk_widget_show (fixed59);
  gtk_container_add (GTK_CONTAINER (acceuiladmin), fixed59);

  centre = gtk_button_new_with_mnemonic (_("GESTION DES CENTRES"));
  gtk_widget_show (centre);
  gtk_fixed_put (GTK_FIXED (fixed59), centre, 64, 592);
  gtk_widget_set_size_request (centre, 464, 208);

  evenement = gtk_button_new_with_mnemonic (_("GESTION DES EVENEMENTS"));
  gtk_widget_show (evenement);
  gtk_fixed_put (GTK_FIXED (fixed59), evenement, 1304, 576);
  gtk_widget_set_size_request (evenement, 464, 208);

  equipement = gtk_button_new_with_mnemonic (_("GESTION DES EQUIPEMENTS"));
  gtk_widget_show (equipement);
  gtk_fixed_put (GTK_FIXED (fixed59), equipement, 1280, 184);
  gtk_widget_set_size_request (equipement, 464, 208);

  label598 = gtk_label_new (_("WELCOME!"));
  gtk_widget_show (label598);
  gtk_fixed_put (GTK_FIXED (fixed59), label598, 792, 48);
  gtk_widget_set_size_request (label598, 176, 49);

  membre = gtk_button_new_with_mnemonic (_("GESTION DES MEMBRES"));
  gtk_widget_show (membre);
  gtk_fixed_put (GTK_FIXED (fixed59), membre, 64, 176);
  gtk_widget_set_size_request (membre, 464, 208);

  entraineur = gtk_button_new_with_mnemonic (_("GESTION DES ENTRAINEURS"));
  gtk_widget_show (entraineur);
  gtk_fixed_put (GTK_FIXED (fixed59), entraineur, 680, 176);
  gtk_widget_set_size_request (entraineur, 464, 208);

  cours = gtk_button_new_with_mnemonic (_("GESTION DES COURS SPORTIFS"));
  gtk_widget_show (cours);
  gtk_fixed_put (GTK_FIXED (fixed59), cours, 680, 592);
  gtk_widget_set_size_request (cours, 464, 208);

  home3 = gtk_button_new ();
  gtk_widget_show (home3);
  gtk_fixed_put (GTK_FIXED (fixed59), home3, 1624, 40);
  gtk_widget_set_size_request (home3, 80, 48);

  image77 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image77);
  gtk_container_add (GTK_CONTAINER (home3), image77);

  g_signal_connect ((gpointer) membre, "clicked",
                    G_CALLBACK (on_membre_clicked),
                    NULL);
  g_signal_connect ((gpointer) home3, "clicked",
                    G_CALLBACK (on_home3_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuiladmin, acceuiladmin, "acceuiladmin");
  GLADE_HOOKUP_OBJECT (acceuiladmin, fixed59, "fixed59");
  GLADE_HOOKUP_OBJECT (acceuiladmin, centre, "centre");
  GLADE_HOOKUP_OBJECT (acceuiladmin, evenement, "evenement");
  GLADE_HOOKUP_OBJECT (acceuiladmin, equipement, "equipement");
  GLADE_HOOKUP_OBJECT (acceuiladmin, label598, "label598");
  GLADE_HOOKUP_OBJECT (acceuiladmin, membre, "membre");
  GLADE_HOOKUP_OBJECT (acceuiladmin, entraineur, "entraineur");
  GLADE_HOOKUP_OBJECT (acceuiladmin, cours, "cours");
  GLADE_HOOKUP_OBJECT (acceuiladmin, home3, "home3");
  GLADE_HOOKUP_OBJECT (acceuiladmin, image77, "image77");

  return acceuiladmin;
}

GtkWidget*
create_acceuilmembre (void)
{
  GtkWidget *acceuilmembre;
  GtkWidget *fixed60;
  GtkWidget *evenementp;
  GtkWidget *coursins;
  GtkWidget *demande;
  GtkWidget *label599;
  GtkWidget *home4;
  GtkWidget *image78;

  acceuilmembre = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuilmembre), _("acceuilmembre"));

  fixed60 = gtk_fixed_new ();
  gtk_widget_show (fixed60);
  gtk_container_add (GTK_CONTAINER (acceuilmembre), fixed60);

  evenementp = gtk_button_new_with_mnemonic (_("PARTICIPER A UN EVENEMENT"));
  gtk_widget_show (evenementp);
  gtk_fixed_put (GTK_FIXED (fixed60), evenementp, 480, 408);
  gtk_widget_set_size_request (evenementp, 880, 168);

  coursins = gtk_button_new_with_mnemonic (_("S'INSCRIRE A UN COURS"));
  gtk_widget_show (coursins);
  gtk_fixed_put (GTK_FIXED (fixed60), coursins, 480, 168);
  gtk_widget_set_size_request (coursins, 880, 168);

  demande = gtk_button_new_with_mnemonic (_("DEMANDER UN COACH PRIVE"));
  gtk_widget_show (demande);
  gtk_fixed_put (GTK_FIXED (fixed60), demande, 488, 648);
  gtk_widget_set_size_request (demande, 880, 168);

  label599 = gtk_label_new (_("WELCOME !"));
  gtk_widget_show (label599);
  gtk_fixed_put (GTK_FIXED (fixed60), label599, -8, -8);
  gtk_widget_set_size_request (label599, 1856, 120);

  home4 = gtk_button_new ();
  gtk_widget_show (home4);
  gtk_fixed_put (GTK_FIXED (fixed60), home4, 1568, 24);
  gtk_widget_set_size_request (home4, 72, 48);

  image78 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image78);
  gtk_container_add (GTK_CONTAINER (home4), image78);

  g_signal_connect ((gpointer) demande, "clicked",
                    G_CALLBACK (on_demande_clicked),
                    NULL);
  g_signal_connect ((gpointer) home4, "clicked",
                    G_CALLBACK (on_home4_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuilmembre, acceuilmembre, "acceuilmembre");
  GLADE_HOOKUP_OBJECT (acceuilmembre, fixed60, "fixed60");
  GLADE_HOOKUP_OBJECT (acceuilmembre, evenementp, "evenementp");
  GLADE_HOOKUP_OBJECT (acceuilmembre, coursins, "coursins");
  GLADE_HOOKUP_OBJECT (acceuilmembre, demande, "demande");
  GLADE_HOOKUP_OBJECT (acceuilmembre, label599, "label599");
  GLADE_HOOKUP_OBJECT (acceuilmembre, home4, "home4");
  GLADE_HOOKUP_OBJECT (acceuilmembre, image78, "image78");

  return acceuilmembre;
}

GtkWidget*
create_acceuilentraineur (void)
{
  GtkWidget *acceuilentraineur;
  GtkWidget *fixed61;
  GtkWidget *label602;
  GtkWidget *button2;
  GtkWidget *button1;
  GtkWidget *button3;

  acceuilentraineur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (acceuilentraineur), _("acceuilentraineur"));

  fixed61 = gtk_fixed_new ();
  gtk_widget_show (fixed61);
  gtk_container_add (GTK_CONTAINER (acceuilentraineur), fixed61);

  label602 = gtk_label_new (_("WELCOME!"));
  gtk_widget_show (label602);
  gtk_fixed_put (GTK_FIXED (fixed61), label602, 832, 16);
  gtk_widget_set_size_request (label602, 201, 41);

  button2 = gtk_button_new_with_mnemonic (_("button2"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed61), button2, 504, 328);
  gtk_widget_set_size_request (button2, 888, 189);

  button1 = gtk_button_new_with_mnemonic (_("button1"));
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed61), button1, 504, 104);
  gtk_widget_set_size_request (button1, 888, 189);

  button3 = gtk_button_new_with_mnemonic (_("button3"));
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed61), button3, 504, 568);
  gtk_widget_set_size_request (button3, 888, 189);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (acceuilentraineur, acceuilentraineur, "acceuilentraineur");
  GLADE_HOOKUP_OBJECT (acceuilentraineur, fixed61, "fixed61");
  GLADE_HOOKUP_OBJECT (acceuilentraineur, label602, "label602");
  GLADE_HOOKUP_OBJECT (acceuilentraineur, button2, "button2");
  GLADE_HOOKUP_OBJECT (acceuilentraineur, button1, "button1");
  GLADE_HOOKUP_OBJECT (acceuilentraineur, button3, "button3");

  return acceuilentraineur;
}

