/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_membres (void);
GtkWidget* create_demande_coach (void);
GtkWidget* create_reservation (void);
GtkWidget* create_authentification (void);
GtkWidget* create_acceuiladmin (void);
GtkWidget* create_acceuilmembre (void);
GtkWidget* create_acceuilentraineur (void);
