/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Gestion_membres (void);
GtkWidget* create_demande_coach (void);
GtkWidget* create_reservation (void);
GtkWidget* create_authentification (void);
GtkWidget* create_acceuiladmin (void);
GtkWidget* create_acceuilmembre (void);
GtkWidget* create_acceuilentraineur (void);
GtkWidget* create_gestion_des_equipement (void);
GtkWidget* create_reserver_un_equipement (void);
GtkWidget* create_mes_reservation (void);
GtkWidget* create_window1 (void);
GtkWidget* create_window2 (void);
GtkWidget* create_gestion_centres (void);
